# extend:
#     ../../st_layout.yaml

main:
  "Right Arm Tracking Error":
    legends:
      - { key: rh_st_diff, id: [17], label: collar-y }
      - { key: rh_st_diff, id: [18], label: shoulder-p }
      - { key: rh_st_diff, id: [19], label: shoulder-r }
      - { key: rh_st_diff, id: [20], label: shoulder-y }
      - { key: rh_st_diff, id: [21], label: elbow-p }
      - { key: rh_st_diff, id: [22], label: wrist-y }
      - { key: rh_st_diff, id: [23], label: wrist-r }
      - { key: rh_st_diff, id: [24], label: wrist-p }
    label: "Tracking Error [deg]"
    width: 140mm
    height: 70mm

  "Left Arm Tracking Error":
    legends:
      - { key: rh_st_diff, id: [25], label: collar-y }
      - { key: rh_st_diff, id: [26], label: shoulder-p }
      - { key: rh_st_diff, id: [27], label: shoulder-r }
      - { key: rh_st_diff, id: [28], label: shoulder-y }
      - { key: rh_st_diff, id: [29], label: elbow-p }
      - { key: rh_st_diff, id: [30], label: wrist-y }
      - { key: rh_st_diff, id: [31], label: wrist-r }
      - { key: rh_st_diff, id: [32], label: wrist-p }
    label: "Tracking Error [deg]"
    width: 140mm
    height: 70mm

  "Torso Tracking Error":
    legends:
      - { key: rh_st_diff, id: [12], label: waist-r }
      - { key: rh_st_diff, id: [13], label: waist-p }
      - { key: rh_st_diff, id: [14], label: waist-r }
    label: "Tracking Error [deg]"
    width: 140mm
    height: 70mm

  "Right Arm Estimated Joint Torques":
    legends:
      - { key: tau, id: [17], label: collar-y }
      - { key: tau, id: [18], label: shoulder-p }
      - { key: tau, id: [19], label: shoulder-r }
      - { key: tau, id: [20], label: shoulder-y }
      - { key: tau, id: [21], label: elbow-p }
      - { key: tau, id: [22], label: wrist-y }
      - { key: tau, id: [23], label: wrist-r }
      - { key: tau, id: [24], label: wrist-p }
    label: "Joint Torques [Nm]"
    width: 140mm
    height: 70mm

  "Left Arm Estimated Joint Torques":
    legends:
      - { key: tau, id: [25], label: collar-y }
      - { key: tau, id: [26], label: shoulder-p }
      - { key: tau, id: [27], label: shoulder-r }
      - { key: tau, id: [28], label: shoulder-y }
      - { key: tau, id: [29], label: elbow-p }
      - { key: tau, id: [30], label: wrist-y }
      - { key: tau, id: [31], label: wrist-r }
      - { key: tau, id: [32], label: wrist-p }
    label: "Joint Torques [Nm]"
    width: 140mm
    height: 70mm

  "Torso Estimated Joint Torques":
    legends:
      - { key: tau, id: [12], label: waist-r }
      - { key: tau, id: [13], label: waist-p }
      - { key: tau, id: [14], label: waist-r }
    label: "Joint Torques [Nm]"
    width: 140mm
    height: 70mm


  # "Right Arm Joint Velocities":
  #   legends:
  #     - { key: jvel, id: [17], label: collar-y }
  #     - { key: jvel, id: [18], label: shoulder-p }
  #     - { key: jvel, id: [19], label: shoulder-r }
  #     - { key: jvel, id: [20], label: shoulder-y }
  #     - { key: jvel, id: [21], label: elbow-p }
  #     - { key: jvel, id: [22], label: wrist-y }
  #     - { key: jvel, id: [23], label: wrist-r }
  #     - { key: jvel, id: [24], label: wrist-p }
  #   label: "Joint Velocities [deg/s]"
  #   width: 140mm
  #   height: 70mm

  # "Left Arm Joint Velocities":
  #   legends:
  #     - { key: jvel, id: [25], label: collar-y }
  #     - { key: jvel, id: [26], label: shoulder-p }
  #     - { key: jvel, id: [27], label: shoulder-r }
  #     - { key: jvel, id: [28], label: shoulder-y }
  #     - { key: jvel, id: [29], label: elbow-p }
  #     - { key: jvel, id: [30], label: wrist-y }
  #     - { key: jvel, id: [31], label: wrist-r }
  #     - { key: jvel, id: [32], label: wrist-p }
  #   label: "Joint Velocities [deg/s]"
  #   width: 140mm
  #   height: 70mm

  # "Torso Joint Velocities":
  #   legends:
  #     - { key: jvel, id: [12], label: waist-r }
  #     - { key: jvel, id: [13], label: waist-p }
  #     - { key: jvel, id: [14], label: waist-r }
  #   label: "Joint Velocities [deg/s]"
  #   width: 140mm
  #   height: 70mm

  # "Velocity in the n Direction":
  #   legends:
  #     - { key: hit_point_vel, id: [0], label: velocity }
  #   label: "Velocity [m/s]"
  #   width: 140mm
  #   height: 70mm

