# extend:
#     ../../st_layout.yaml

main:
#   rleg_joint_angle:
#     legends:
#       - { key: sh_qOut, id: [0-5] }
#       - { key: abc_q, id: [0-5] }
#       - { key: st_q, id: [0-5] }
#       - { key: RobotHardware0_q, id: [0-5] }

#   lleg_joint_angle:
#     legends:
#       - { key: sh_qOut, id: [6-11] }
#       - { key: abc_q, id: [6-11] }
#       - { key: st_q, id: [6-11] }
#       - { key: RobotHardware0_q, id: [6-11] }

#   tracking:
#     legends:
#       - {key: rh_st_diff, id: [0-5] }
#       - {key: abs_enc_diff, id: [0-5] }

#   right_foot_force:
#     legends:
#       - { key: sh_rfsensorOut, id: [0-5] }
#       - { key: RobotHardware0_rfsensor, id: [0-5] }
#       - { key: rmfo_off_rfsensor, id: [0-5] }

#   current:
#     legends:
#       - { key: current, id: [0-5] }

#   imu_gsensor:
#     legends:
#       - { key: imu_gsensor, id: [0], label: x }
#       - { key: imu_gsensor, id: [1], label: y }
#       - { key: imu_gsensor, id: [2], label: z }
#     newline: False

#   imu_gyrometer:
#     legends:
#       - { key: imu_gyrometer, id: [0], label: x }
#       - { key: imu_gyrometer, id: [1], label: y }
#       - { key: imu_gyrometer, id: [2], label: z }

#   temperature:
#     legends:
#       - { key: motor_temp, id: [0-5] }
#       - { key: motor_outer_temp, id: [0-5] }

#   comp:
#     legends:
#       - { key: comp, id: [0-5] }

#   watt:
#     legends:
#       - { key: watt, id: [0-5] }

#   ServoState:
#     legends:
#       - { key: ServoState, id: [0-5] }

#   12V:
#     legends:
#       - { key: 12V, id: [0,1,2,3,4,5] }

#   80V:
#     legends:
#       - { key: 80V, id: [0,1,2,3,4,5] }

#   ZMP:
#     legends:
#       - { key: st_zmp, id: [0,1] }
  "Right Arm Joint Velocities":
    legends:
      - { key: jvel, id: [17], label: collar-y }
      - { key: jvel, id: [18], label: shoulder-p }
      - { key: jvel, id: [19], label: shoulder-r }
      - { key: jvel, id: [20], label: shoulder-y }
      - { key: jvel, id: [21], label: elbow-p }
      - { key: jvel, id: [22], label: wrist-y }
      - { key: jvel, id: [23], label: wrist-r }
      - { key: jvel, id: [24], label: wrist-p }
    label: "Joint Velocities [deg/s]"
    width: 140mm
    height: 70mm

  "Left Arm Joint Velocities":
    legends:
      - { key: jvel, id: [25], label: collar-y }
      - { key: jvel, id: [26], label: shoulder-p }
      - { key: jvel, id: [27], label: shoulder-r }
      - { key: jvel, id: [28], label: shoulder-y }
      - { key: jvel, id: [29], label: elbow-p }
      - { key: jvel, id: [30], label: wrist-y }
      - { key: jvel, id: [31], label: wrist-r }
      - { key: jvel, id: [32], label: wrist-p }
    label: "Joint Velocities [deg/s]"
    width: 140mm
    height: 70mm

  "Torso Joint Velocities":
    legends:
      - { key: jvel, id: [12], label: waist-r }
      - { key: jvel, id: [13], label: waist-p }
      - { key: jvel, id: [14], label: waist-r }
    label: "Joint Velocities [deg/s]"
    width: 140mm
    height: 70mm
